import type { Metadata } from "next";
import "./globals.css";
import logo from "@/public/logo.png"
import { sanityFetch, SanityLive } from "@/sanity/lib/live";
import { draftMode } from "next/headers";
import { DisableDraftMode } from "@/components/preview/DisableDraftMode";
import { Header_Query } from "@/sanity/lib/queries/navigation";
import { ThemeProvider } from "@/components/global/ThemeProvider";
import Header from "@/components/navigation/Header";
import { VisualEditing } from "next-sanity/visual-editing";


export const metadata: Metadata = {
  title: "Next sanity Ecommerce",
  description: "Generated by create next app",
  icons: {
    icon: logo.src
  }
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isEnabled = await draftMode()
  const { data: header } = await sanityFetch({
    query: Header_Query,
  });
  return (
    <html lang="en">
      <body
        className={``}
      >
        <ThemeProvider>
          <Header header={header} />
          {children}
            <SanityLive />
            {(await draftMode()).isEnabled && <VisualEditing />}
        </ThemeProvider>
      </body>
    </html>
  );
}
